AUDIO_ENABLE = no        # Audio output on port C6
BACKLIGHT_ENABLE = no    # Enable keyboard backlight functionality
BLUETOOTH_ENABLE = no    # Enable Bluetooth with the Adafruit EZ-Key HID
BOOTMAGIC_ENABLE = lite  # Just bootloader enabled with keys
COMMAND_ENABLE = no      # Commands for debug and configuration
CONSOLE_ENABLE = no      # Console for debug
EXTRAKEY_ENABLE = yes    # Audio control and System control
FAUXCLICKY_ENABLE = no   # Use buzzer to emulate clicky switches
JOYSTICK_ENABLE = no     # Joystick emulation (digital/analog)
MIDI_ENABLE = yes        # MIDI support 
MOUSEKEY_ENABLE = yes    # Mouse keys
NKRO_ENABLE = yes        # USB Nkey Rollover (if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work)
RGBLED_NUM = 10          # The number of LEDs connected
RGBLIGHT_DRIVER = WS2812B  #  check your type
RGBLIGHT_ENABLE = yes    # keys lights
RGB_DI_PIN = D5          # The pin connected to the data pin of the LEDs
SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend (it uses the same timer as BACKLIGHT_ENABLE)
TAP_DANCE_ENABLE = no    # tap dancing functions
UNICODE_ENABLE = no      # Unicode
